package com.sdl.sdlarchivesmanager;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ADDRESS".
 */
public class Address {

    private Long id;
    private String Addr_Code;
    private String Addr_Name;
    private String Addr_UpCode;
    private String Addr_Level;

    public Address() {
    }

    public Address(Long id, String Addr_Code) {
        this.id = id;
        this.Addr_Code = Addr_Code;
    }

    public Address(Long id, String Addr_Code, String Addr_Name, String Addr_UpCode, String Addr_Level) {
        this.id = id;
        this.Addr_Code = Addr_Code;
        this.Addr_Name = Addr_Name;
        this.Addr_UpCode = Addr_UpCode;
        this.Addr_Level = Addr_Level;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAddr_Code() {
        return Addr_Code;
    }

    public void setAddr_Code(String Addr_Code) {
        this.Addr_Code = Addr_Code;
    }

    public String getAddr_Name() {
        return Addr_Name;
    }

    public void setAddr_Name(String Addr_Name) {
        this.Addr_Name = Addr_Name;
    }

    public String getAddr_UpCode() {
        return Addr_UpCode;
    }

    public void setAddr_UpCode(String Addr_UpCode) {
        this.Addr_UpCode = Addr_UpCode;
    }

    public String getAddr_Level() {
        return Addr_Level;
    }

    public void setAddr_Level(String Addr_Level) {
        this.Addr_Level = Addr_Level;
    }

}
