package com.sdl.sdlarchivesmanager;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BANK".
 */
public class Bank {

    private Long id;
    private String Bank_ClientNum;
    private String Bank_Num;
    private String Bank_Name;
    private String Bank_Name2;
    private String Bank_Phone;
    private String Bank_Invoice;

    public Bank() {
    }

    public Bank(Long id) {
        this.id = id;
    }

    public Bank(Long id, String Bank_ClientNum, String Bank_Num, String Bank_Name, String Bank_Name2, String Bank_Phone, String Bank_Invoice) {
        this.id = id;
        this.Bank_ClientNum = Bank_ClientNum;
        this.Bank_Num = Bank_Num;
        this.Bank_Name = Bank_Name;
        this.Bank_Name2 = Bank_Name2;
        this.Bank_Phone = Bank_Phone;
        this.Bank_Invoice = Bank_Invoice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBank_ClientNum() {
        return Bank_ClientNum;
    }

    public void setBank_ClientNum(String Bank_ClientNum) {
        this.Bank_ClientNum = Bank_ClientNum;
    }

    public String getBank_Num() {
        return Bank_Num;
    }

    public void setBank_Num(String Bank_Num) {
        this.Bank_Num = Bank_Num;
    }

    public String getBank_Name() {
        return Bank_Name;
    }

    public void setBank_Name(String Bank_Name) {
        this.Bank_Name = Bank_Name;
    }

    public String getBank_Name2() {
        return Bank_Name2;
    }

    public void setBank_Name2(String Bank_Name2) {
        this.Bank_Name2 = Bank_Name2;
    }

    public String getBank_Phone() {
        return Bank_Phone;
    }

    public void setBank_Phone(String Bank_Phone) {
        this.Bank_Phone = Bank_Phone;
    }

    public String getBank_Invoice() {
        return Bank_Invoice;
    }

    public void setBank_Invoice(String Bank_Invoice) {
        this.Bank_Invoice = Bank_Invoice;
    }

}
