package com.sdl.sdlarchivesmanager;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sdl.sdlarchivesmanager.User;
import com.sdl.sdlarchivesmanager.Client;
import com.sdl.sdlarchivesmanager.Bank;
import com.sdl.sdlarchivesmanager.Application;

import com.sdl.sdlarchivesmanager.UserDao;
import com.sdl.sdlarchivesmanager.ClientDao;
import com.sdl.sdlarchivesmanager.BankDao;
import com.sdl.sdlarchivesmanager.ApplicationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig clientDaoConfig;
    private final DaoConfig bankDaoConfig;
    private final DaoConfig applicationDaoConfig;

    private final UserDao userDao;
    private final ClientDao clientDao;
    private final BankDao bankDao;
    private final ApplicationDao applicationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        clientDaoConfig = daoConfigMap.get(ClientDao.class).clone();
        clientDaoConfig.initIdentityScope(type);

        bankDaoConfig = daoConfigMap.get(BankDao.class).clone();
        bankDaoConfig.initIdentityScope(type);

        applicationDaoConfig = daoConfigMap.get(ApplicationDao.class).clone();
        applicationDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        clientDao = new ClientDao(clientDaoConfig, this);
        bankDao = new BankDao(bankDaoConfig, this);
        applicationDao = new ApplicationDao(applicationDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Client.class, clientDao);
        registerDao(Bank.class, bankDao);
        registerDao(Application.class, applicationDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        clientDaoConfig.getIdentityScope().clear();
        bankDaoConfig.getIdentityScope().clear();
        applicationDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ClientDao getClientDao() {
        return clientDao;
    }

    public BankDao getBankDao() {
        return bankDao;
    }

    public ApplicationDao getApplicationDao() {
        return applicationDao;
    }

}
