package com.sdl.sdlarchivesmanager;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String User_Num;
    private String User_Pass;
    private String User_Name;
    private String User_Regin;
    private String User_Role;
    private java.util.Date User_Date;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String User_Num, String User_Pass, String User_Name, String User_Regin, String User_Role, java.util.Date User_Date) {
        this.id = id;
        this.User_Num = User_Num;
        this.User_Pass = User_Pass;
        this.User_Name = User_Name;
        this.User_Regin = User_Regin;
        this.User_Role = User_Role;
        this.User_Date = User_Date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUser_Num() {
        return User_Num;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_Num(String User_Num) {
        this.User_Num = User_Num;
    }

    public String getUser_Pass() {
        return User_Pass;
    }

    public void setUser_Pass(String User_Pass) {
        this.User_Pass = User_Pass;
    }

    public String getUser_Name() {
        return User_Name;
    }

    public void setUser_Name(String User_Name) {
        this.User_Name = User_Name;
    }

    public String getUser_Regin() {
        return User_Regin;
    }

    public void setUser_Regin(String User_Regin) {
        this.User_Regin = User_Regin;
    }

    public String getUser_Role() {
        return User_Role;
    }

    public void setUser_Role(String User_Role) {
        this.User_Role = User_Role;
    }

    public java.util.Date getUser_Date() {
        return User_Date;
    }

    public void setUser_Date(java.util.Date User_Date) {
        this.User_Date = User_Date;
    }

}
